<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select Date_datePickerMonthYearInput</name>
   <tag></tag>
   <elementGuidId>86912434-2521-4846-9a89-b12204618fa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datePickerMonthYearInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datePickerMonthYearInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9541feba-003c-4cce-b741-3ac7d438bda6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>91cfe22a-4cac-4f22-bc78-4cb4174fe548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datePickerMonthYearInput</value>
      <webElementGuid>bb2399c7-87e5-4f68-9104-e2f7322acffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>dbb6a6e1-aea6-49ac-b0ab-a51f30a0e8cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>07/21/2023</value>
      <webElementGuid>86adcc93-dd51-4e61-ba22-7e22d8b72f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datePickerMonthYearInput&quot;)</value>
      <webElementGuid>805237f3-cbed-425b-8b20-7962fb7c5c87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datePickerMonthYearInput']</value>
      <webElementGuid>1ff5aff6-5833-41fa-a9e5-e58db14103ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datePickerMonthYear']/div/div/input</value>
      <webElementGuid>bb4f1462-e2cc-47de-9e48-b3ed09e54af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0634cf6d-c346-422d-8e4f-918d0e3ded35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'datePickerMonthYearInput']</value>
      <webElementGuid>154b29b6-3b8e-4c84-9dba-d152fa27341b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
