<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date And Time_dateAndTimePickerInput</name>
   <tag></tag>
   <elementGuidId>b33dd997-6563-4d44-9e47-8a77c532927d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dateAndTimePickerInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dateAndTimePickerInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dee92d3f-8664-48c0-ab73-d4f9bc85bb05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e660aea1-43c4-4f94-af19-ae6154d57405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dateAndTimePickerInput</value>
      <webElementGuid>df1e627e-6766-42d1-98c3-6689c70eba2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>3f5ac355-5262-4998-94ff-b60098592a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>July 21, 2023 3:38 PM</value>
      <webElementGuid>385254cb-afe2-4a62-b52c-977a19c9e4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dateAndTimePickerInput&quot;)</value>
      <webElementGuid>4bbbedd8-3601-40a9-aa29-595a67705228</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dateAndTimePickerInput']</value>
      <webElementGuid>cb3bd3ba-84f6-4dbd-bd85-e37a7223b61c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dateAndTimePicker']/div/div/input</value>
      <webElementGuid>d5a59f5a-6b29-4ef2-9e60-7ef2ec6893b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>9f7f31ed-cac8-44c5-98a5-db70704376e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dateAndTimePickerInput']</value>
      <webElementGuid>75ee800a-b56f-4b2e-84e9-fe2ea88dd8a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
